'use strict';
const canvas=document.getElementById('mapCanvas');
const ctx=canvas.getContext('2d',{alpha:false});
const savedRoute=JSON.parse(localStorage.getItem('atlas.route')||'[]');
const state={locations:[],categories:[],regions:[],categoryMap:new Map(),regionMap:new Map(),enabled:new Set(),favorites:new Set(JSON.parse(localStorage.getItem('atlas.favorites')||'[]')),discovered:new Set(JSON.parse(localStorage.getItem('atlas.discovered')||'[]')),routeIds:savedRoute,route:[],mode:'all',scale:1,offsetX:0,offsetY:0,minScale:.35,maxScale:7,drag:false,moved:false,lastX:0,lastY:0,pointers:new Map(),pinchDistance:0,selected:null,image:new Image(),imageReady:false,sheetLevel:'peek',clusters:[],framePending:false};
const el=id=>document.getElementById(id);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fitScale=()=>Math.min(innerWidth/4096,innerHeight/4096)*1.1;
function resize(){const dpr=Math.min(devicePixelRatio||1,2.5);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0);if(!state.offsetX&&!state.offsetY)fitMap();scheduleDraw()}
function fitMap(){const s=fitScale();state.scale=s;state.offsetX=(innerWidth-4096*s)/2;state.offsetY=(innerHeight-4096*s)/2;updateZoomLabel()}
function mapToScreen(loc){return{x:state.offsetX+loc.atlas_x*4096*state.scale,y:state.offsetY+loc.atlas_y*4096*state.scale}}
function iconType(cat=''){return AtlasIcons.type(cat)}
function categoryGroup(title=''){const g=AtlasIcons.group(iconType(title));return g==='location'?'locations':g==='collectible'?'collectibles':g==='activity'||g==='enemy'?'activities':'other'}
function visibleLocations(){return state.locations.filter(l=>state.enabled.has(l.category_id)&&(state.mode==='all'||state.mode==='favorites'&&state.favorites.has(l.id)||state.mode!=='favorites'&&categoryGroup(state.categoryMap.get(l.category_id)?.title)===state.mode))}
function buildClusters(list){const relative=state.scale/fitScale();if(relative>=3.15)return list.map(l=>{const p=mapToScreen(l);return{x:p.x,y:p.y,count:1,items:[l]}});const cell=relative<.8?86:relative<1.5?66:50,buckets=new Map();for(const l of list){const p=mapToScreen(l);if(p.x<-90||p.y<-90||p.x>innerWidth+90||p.y>innerHeight+90)continue;const key=`${Math.floor(p.x/cell)}:${Math.floor(p.y/cell)}`;let b=buckets.get(key);if(!b)buckets.set(key,b={x:0,y:0,count:0,items:[]});b.x+=p.x;b.y+=p.y;b.count++;b.items.push(l)}return[...buckets.values()].map(b=>({...b,x:b.x/b.count,y:b.y/b.count}))}
function scheduleDraw(){if(state.framePending)return;state.framePending=true;requestAnimationFrame(()=>{state.framePending=false;draw()})}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawCluster(c){const r=clamp(17+Math.log2(c.count)*3,19,32);ctx.save();ctx.shadowColor='rgba(0,0,0,.48)';ctx.shadowBlur=14;ctx.shadowOffsetY=5;ctx.beginPath();ctx.arc(c.x,c.y,r+3,0,Math.PI*2);ctx.fillStyle='rgba(19,16,15,.9)';ctx.fill();ctx.shadowColor='transparent';ctx.beginPath();ctx.arc(c.x,c.y,r,0,Math.PI*2);const g=ctx.createRadialGradient(c.x-6,c.y-7,2,c.x,c.y,r);g.addColorStop(0,'#dc4b58');g.addColorStop(1,'#79131d');ctx.fillStyle=g;ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='rgba(255,242,222,.88)';ctx.stroke();ctx.fillStyle='#fff8ee';ctx.font='700 12px -apple-system,BlinkMacSystemFont,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(c.count>999?'999+':String(c.count),c.x,c.y+.5);ctx.restore()}
function lighten(hex,amount){const n=parseInt(hex.slice(1),16),r=Math.min(255,(n>>16)+amount),g=Math.min(255,((n>>8)&255)+amount),b=Math.min(255,(n&255)+amount);return`rgb(${r},${g},${b})`}
function drawRoute(){if(state.route.length<2)return;const pts=state.route.map(mapToScreen);ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash([10,8]);ctx.lineDashOffset=-(performance.now()/70)%18;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle='rgba(19,14,11,.8)';ctx.lineWidth=8;ctx.stroke();ctx.strokeStyle='#e6bd70';ctx.lineWidth=3;ctx.stroke();ctx.setLineDash([]);pts.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,i===0||i===pts.length-1?10:8,0,Math.PI*2);ctx.fillStyle=i===0?'#d6aa56':i===pts.length-1?'#f2e7d3':'#a9212e';ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='#fff4df';ctx.stroke();ctx.fillStyle=i===0||i===pts.length-1?'#20170d':'white';ctx.font='800 10px -apple-system,BlinkMacSystemFont,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(i+1),p.x,p.y+.5)});ctx.restore();requestAnimationFrame(scheduleDraw)}
function drawMarker(c,relative){const l=c.items[0],cat=state.categoryMap.get(l.category_id)?.title||'',icon=iconType(cat),selected=l.id===state.selected?.id,discovered=state.discovered.has(l.id),favorite=state.favorites.has(l.id),inRoute=state.route.some(x=>x.id===l.id);const r=selected?18:relative<1?10.5:12.5,base=discovered?'#625f5b':AtlasIcons.color(icon);ctx.save();ctx.shadowColor=selected?'rgba(224,60,72,.62)':'rgba(0,0,0,.5)';ctx.shadowBlur=selected?18:8;ctx.shadowOffsetY=selected?0:3;ctx.beginPath();ctx.arc(c.x,c.y,r+3,0,Math.PI*2);ctx.fillStyle=selected?'rgba(255,245,228,.95)':'rgba(18,16,15,.88)';ctx.fill();ctx.shadowColor='transparent';ctx.beginPath();ctx.arc(c.x,c.y,r,0,Math.PI*2);const grad=ctx.createRadialGradient(c.x-r*.35,c.y-r*.4,1,c.x,c.y,r);grad.addColorStop(0,discovered?'#817c76':lighten(base,26));grad.addColorStop(1,base);ctx.fillStyle=grad;ctx.fill();ctx.lineWidth=selected?2.3:1.4;ctx.strokeStyle=inRoute?'#edc574':selected?'#fff7e8':'rgba(255,239,218,.72)';ctx.stroke();if(relative>.72||selected)AtlasIcons.draw(ctx,icon,c.x,c.y,selected?22:15,{alpha:discovered?.72:1});else{ctx.beginPath();ctx.arc(c.x,c.y,2.3,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}if(favorite){ctx.beginPath();ctx.arc(c.x+r*.7,c.y-r*.72,4.2,0,Math.PI*2);ctx.fillStyle='#d9af62';ctx.fill();ctx.strokeStyle='#fff5e6';ctx.stroke()}if(selected){ctx.beginPath();ctx.arc(c.x,c.y,r+7,0,Math.PI*2);ctx.strokeStyle='rgba(236,74,86,.62)';ctx.lineWidth=2;ctx.stroke()}ctx.restore()}
function draw(){ctx.fillStyle='#171512';ctx.fillRect(0,0,innerWidth,innerHeight);if(state.imageReady){ctx.save();ctx.globalAlpha=.92;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(state.image,state.offsetX,state.offsetY,4096*state.scale,4096*state.scale);ctx.restore()}drawRoute();const list=visibleLocations(),relative=state.scale/fitScale();state.clusters=buildClusters(list);for(const c of state.clusters){if(c.x<-45||c.y<-45||c.x>innerWidth+45||c.y>innerHeight+45)continue;c.count>1?drawCluster(c):drawMarker(c,relative)}el('visibleCount').textContent=list.length}
function zoomAt(factor,x=innerWidth/2,y=innerHeight/2){const old=state.scale,next=clamp(old*factor,state.minScale,state.maxScale),mx=(x-state.offsetX)/old,my=(y-state.offsetY)/old;state.scale=next;state.offsetX=x-mx*next;state.offsetY=y-my*next;updateZoomLabel();scheduleDraw()}
function updateZoomLabel(){el('zoomLabel').textContent='×'+(state.scale/fitScale()).toFixed(state.scale/fitScale()<10?1:0)}
function pickTarget(x,y){let best=null,dist=42;for(const c of state.clusters){const d=Math.hypot(c.x-x,c.y-y);if(d<dist){dist=d;best=c}}return best}
function focusLocation(l,scale=.85){state.scale=Math.max(state.scale,scale);const p=mapToScreen(l);state.offsetX+=innerWidth/2-p.x;state.offsetY+=innerHeight/2-p.y;selectLocation(l)}
function expandCluster(c){const avgX=c.items.reduce((a,l)=>a+l.atlas_x,0)/c.count,avgY=c.items.reduce((a,l)=>a+l.atlas_y,0)/c.count;state.scale=clamp(state.scale*1.9,state.minScale,state.maxScale);state.offsetX=innerWidth/2-avgX*4096*state.scale;state.offsetY=innerHeight/2-avgY*4096*state.scale;updateZoomLabel();scheduleDraw()}
function parseDescription(s=''){const safe=escapeHTML(s).replace(/\[([^\]]+)\]\([^\)]+\)/g,'$1').replace(/\*\*(.*?)\*\*/g,'<b>$1</b>').replace(/\n/g,'<br>'),reward=(s.match(/\*\*Rewards:\*\*([\s\S]*?)(?:\n\n|$)/i)||[])[1];return{html:safe,reward:reward?escapeHTML(reward.trim()).replace(/^- /gm,'').replace(/\n/g,' · '):'尚未整理奖励信息'}}
function iconMarkup(title,size=24){const icon=iconType(title);return`<span class="atlas-icon-wrap" style="--icon-color:${AtlasIcons.color(icon)}">${AtlasIcons.svg(icon,size)}</span>`}
function selectLocation(l){if(!l)return;state.selected=l;const c=state.categoryMap.get(l.category_id),r=state.regionMap.get(l.region_id),d=parseDescription(l.description||'暂无详细说明。'),inRoute=state.route.some(x=>x.id===l.id);el('detailContent').innerHTML=`<button class="sheet-close" onclick="closeSheet()">×</button><div class="sheet-title"><div class="sheet-icon">${iconMarkup(c?.title,28)}</div><div><h2>${escapeHTML(l.title)}</h2><p>${escapeHTML(c?.title||'Unknown')} · ${escapeHTML(r?.title||'未知区域')}</p></div></div><div class="sheet-actions"><button class="primary" onclick="toggleDiscovered('${l.id}')">${state.discovered.has(l.id)?'已发现':'标记发现'}</button><button onclick="toggleFavorite('${l.id}')">${state.favorites.has(l.id)?'已收藏':'收藏'}</button><button class="route-add-btn ${inRoute?'active':''}" onclick="toggleRoutePoint('${l.id}')">${inRoute?'移出路线':'加入路线'}</button></div><div class="sheet-highlight"><small>奖励摘要</small><b>${d.reward}</b></div><div class="sheet-description">${d.html}</div><div class="future-block"><small>ATLAS ROUTE</small><b>${AtlasIcons.svg('route',18)} Route Engine 已启用</b><p>加入多个地点后，可自动优化顺序并查看总距离与预计时间。</p></div>`;setSheetLevel('peek');el('detailSheet').classList.add('open');el('detailSheet').setAttribute('aria-hidden','false');scheduleDraw()}
function setSheetLevel(level){state.sheetLevel=level;el('detailSheet').dataset.level=level;document.querySelectorAll('.sheet-levels button').forEach(b=>b.classList.toggle('active',b.dataset.level===level))}
window.closeSheet=()=>{el('detailSheet').classList.remove('open');el('detailSheet').setAttribute('aria-hidden','true');state.selected=null;scheduleDraw()};
window.toggleFavorite=id=>{state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('atlas.favorites',JSON.stringify([...state.favorites]));selectLocation(state.selected);toast(state.favorites.has(id)?'已加入收藏':'已取消收藏')};
window.toggleDiscovered=id=>{state.discovered.has(id)?state.discovered.delete(id):state.discovered.add(id);localStorage.setItem('atlas.discovered',JSON.stringify([...state.discovered]));selectLocation(state.selected);renderProgress();toast(state.discovered.has(id)?'已标记为发现':'已取消发现')};
window.toggleRoutePoint=id=>{const l=state.locations.find(x=>x.id===id);if(!l)return;const exists=state.route.some(x=>x.id===id);state.route=exists?state.route.filter(x=>x.id!==id):[...state.route,l];persistRoute();renderRoute();selectLocation(l);toast(exists?'已移出路线':'已加入路线')};
function persistRoute(){state.routeIds=state.route.map(x=>x.id);localStorage.setItem('atlas.route',JSON.stringify(state.routeIds));scheduleDraw()}
function renderRoute(){const m=AtlasRouteEngine.metrics(state.route);el('routeStops').textContent=m.stops;el('routeDistance').textContent=Math.round(m.distance);el('routeTime').textContent=m.stops?m.minutes+' 分钟':'0 分钟';el('routeList').innerHTML=state.route.length?state.route.map((l,i)=>{const c=state.categoryMap.get(l.category_id),r=state.regionMap.get(l.region_id);return`<div class="route-stop" data-id="${l.id}"><span class="route-stop-index">${i+1}</span><button class="route-stop-copy" data-focus="${l.id}"><b>${escapeHTML(l.title)}</b><small>${escapeHTML(c?.title||'')} · ${escapeHTML(r?.title||'未知区域')}</small></button><button class="route-remove" data-remove="${l.id}">×</button></div>`}).join(''):'<div class="route-empty"><b>路线还是空的</b>打开任意地点详情，点击“加入路线”。</div>';document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{closePanels();focusLocation(state.locations.find(x=>x.id===b.dataset.focus))});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>toggleRoutePoint(b.dataset.remove));el('routeBadge').classList.toggle('show',state.route.length>1);el('routeBadgeText').textContent=state.route.length>1?`${state.route.length} 个点 · 约 ${m.minutes} 分钟`:'路线未建立'}
function optimizeRoute(){if(state.route.length<3){toast('至少加入 3 个地点才能优化');return}state.route=AtlasRouteEngine.optimize(state.route,state.route[0]);persistRoute();renderRoute();toast('路线顺序已优化')}
function focusRoute(){if(!state.route.length){toast('路线还是空的');return}const xs=state.route.map(x=>x.atlas_x*4096),ys=state.route.map(x=>x.atlas_y*4096),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=120;const w=Math.max(260,maxX-minX),h=Math.max(260,maxY-minY);state.scale=clamp(Math.min((innerWidth-pad*2)/w,(innerHeight-pad*2)/h),state.minScale,state.maxScale);state.offsetX=innerWidth/2-((minX+maxX)/2)*state.scale;state.offsetY=innerHeight/2-((minY+maxY)/2)*state.scale;updateZoomLabel();closePanels();scheduleDraw()}
function clearRoute(){state.route=[];persistRoute();renderRoute();toast('路线已清除')}
function escapeHTML(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg){const t=el('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1600)}
function openSearch(){el('searchOverlay').classList.add('open');el('searchOverlay').setAttribute('aria-hidden','false');setTimeout(()=>el('searchInput').focus(),50);runSearch('')}
function closeSearch(){el('searchOverlay').classList.remove('open');el('searchOverlay').setAttribute('aria-hidden','true');el('searchInput').blur()}
function smartTokens(q){const stop=new Set(['所有','全部','的','在','里面','地点','给我','find','show','all','in','the']);return q.toLowerCase().replace(/[，。,.]/g,' ').split(/\s+/).filter(x=>x&&!stop.has(x))}
function runSearch(q){const tokens=smartTokens(q),scored=state.locations.map(l=>{const c=state.categoryMap.get(l.category_id)?.title||'',r=state.regionMap.get(l.region_id)?.title||'',hay=`${l.title} ${c} ${r} ${l.description||''}`.toLowerCase();let score=0;for(const t of tokens){if(l.title.toLowerCase().includes(t))score+=8;if(c.toLowerCase().includes(t))score+=5;if(r.toLowerCase().includes(t))score+=5;if(hay.includes(t))score++}return{l,score}}).filter(x=>!tokens.length||x.score>=tokens.length).sort((a,b)=>b.score-a.score).slice(0,80).map(x=>x.l);el('resultCount').textContent=scored.length+(scored.length===80?'＋':'');el('searchResults').innerHTML=scored.map(l=>{const c=state.categoryMap.get(l.category_id),r=state.regionMap.get(l.region_id);return`<button class="result-item" data-id="${l.id}"><span class="result-icon">${iconMarkup(c?.title,22)}</span><span class="result-copy"><b>${escapeHTML(l.title)}</b><small>${escapeHTML(c?.title||'')} · ${escapeHTML(r?.title||'未知区域')}</small></span><em>›</em></button>`}).join('')||'<div class="empty-state">没有匹配结果</div>';document.querySelectorAll('.result-item').forEach(b=>b.onclick=()=>{const l=state.locations.find(x=>x.id===b.dataset.id);closeSearch();focusLocation(l)})}
function renderCategories(){el('categoryGrid').innerHTML=state.categories.map(c=>`<button class="category-chip ${state.enabled.has(c.id)?'':'off'}" data-id="${c.id}"><span class="category-symbol">${iconMarkup(c.title,18)}</span><b>${escapeHTML(c.title)}</b><small>${c.reported_location_count??0} 个地点</small></button>`).join('');document.querySelectorAll('.category-chip').forEach(b=>b.onclick=()=>{state.enabled.has(b.dataset.id)?state.enabled.delete(b.dataset.id):state.enabled.add(b.dataset.id);b.classList.toggle('off',!state.enabled.has(b.dataset.id));el('filterCount').textContent=state.enabled.size;scheduleDraw()})}
function cleanSavedProgress(){const ids=new Set(state.locations.map(l=>l.id));state.discovered=new Set([...state.discovered].filter(id=>ids.has(id)));state.favorites=new Set([...state.favorites].filter(id=>ids.has(id)));state.route=state.routeIds.map(id=>state.locations.find(l=>l.id===id)).filter(Boolean);localStorage.setItem('atlas.discovered',JSON.stringify([...state.discovered]));localStorage.setItem('atlas.favorites',JSON.stringify([...state.favorites]));persistRoute()}
function renderProgress(){const total=state.locations.length,done=Math.min(state.discovered.size,total),pct=total?clamp(Math.round(done/total*100),0,100):0;el('overallPercent').textContent=pct+'%';el('overallDone').textContent=done;el('overallTotal').textContent=total;el('overallBar').style.width=pct+'%';el('regionProgressList').innerHTML=state.regions.map(r=>{const items=state.locations.filter(l=>l.region_id===r.id),d=items.filter(l=>state.discovered.has(l.id)).length,p=items.length?Math.round(d/items.length*100):0;return`<button class="region-progress" data-region="${r.id}"><div><b>${escapeHTML(r.title)}</b><small>${d} / ${items.length}</small></div><span>${p}%</span><i><em style="width:${p}%"></em></i></button>`}).join('')}
function closePanels(){['filterPanel','progressPanel','routePanel'].forEach(id=>{el(id).classList.remove('open');el(id).setAttribute('aria-hidden','true')})}
function openPanel(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));closePanels();if(name==='filter')el('filterPanel').classList.add('open');else if(name==='route'){renderRoute();el('routePanel').classList.add('open')}else if(name==='favorites'){state.mode='favorites';scheduleDraw();toast('仅显示收藏')}else if(name==='progress'){renderProgress();el('progressPanel').classList.add('open')}}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});state.drag=true;state.moved=false;state.lastX=e.clientX;state.lastY=e.clientY});
canvas.addEventListener('pointermove',e=>{if(!state.pointers.has(e.pointerId))return;const old=state.pointers.get(e.pointerId);if(Math.hypot(e.clientX-old.x,e.clientY-old.y)>4)state.moved=true;state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size===2){const pts=[...state.pointers.values()],d=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y),cx=(pts[0].x+pts[1].x)/2,cy=(pts[0].y+pts[1].y)/2;if(state.pinchDistance)zoomAt(d/state.pinchDistance,cx,cy);state.pinchDistance=d}else if(state.drag){state.offsetX+=e.clientX-state.lastX;state.offsetY+=e.clientY-state.lastY;state.lastX=e.clientX;state.lastY=e.clientY;scheduleDraw()}});
canvas.addEventListener('pointerup',e=>{const start=state.pointers.get(e.pointerId);state.pointers.delete(e.pointerId);if(state.pointers.size<2)state.pinchDistance=0;if(start&&!state.moved){const t=pickTarget(e.clientX,e.clientY);if(t)t.count>1?expandCluster(t):selectLocation(t.items[0]);else closeSheet()}state.drag=false});
canvas.addEventListener('pointercancel',e=>{state.pointers.delete(e.pointerId);state.drag=false;state.pinchDistance=0});canvas.addEventListener('wheel',e=>{e.preventDefault();zoomAt(e.deltaY<0?1.16:.86,e.clientX,e.clientY)},{passive:false});
el('zoomIn').onclick=()=>zoomAt(1.25);el('zoomOut').onclick=()=>zoomAt(.8);el('resetView').onclick=el('locateBtn').onclick=el('brandBtn').onclick=()=>{fitMap();scheduleDraw()};el('searchTrigger').onclick=openSearch;el('closeSearch').onclick=closeSearch;el('searchInput').oninput=e=>runSearch(e.target.value);el('searchOverlay').onclick=e=>{if(e.target===el('searchOverlay'))closeSearch()};
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'){closeSearch();closeSheet();closePanels()}});
document.querySelectorAll('.rail-button').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;document.querySelectorAll('.rail-button').forEach(x=>x.classList.toggle('active',x===b));scheduleDraw()});document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));document.querySelector('.close-panel').onclick=()=>openPanel('map');document.querySelector('.close-progress').onclick=()=>openPanel('map');document.querySelector('.close-route').onclick=()=>openPanel('map');
el('toggleAll').onclick=()=>{if(state.enabled.size){state.enabled.clear();el('toggleAll').textContent='全部显示'}else{state.categories.forEach(c=>state.enabled.add(c.id));el('toggleAll').textContent='全部隐藏'}el('filterCount').textContent=state.enabled.size;renderCategories();scheduleDraw()};
el('sheetHandle').onclick=()=>setSheetLevel(state.sheetLevel==='peek'?'mid':state.sheetLevel==='mid'?'full':'peek');document.querySelectorAll('.sheet-levels button').forEach(b=>b.onclick=()=>setSheetLevel(b.dataset.level));
el('optimizeRoute').onclick=optimizeRoute;el('focusRoute').onclick=focusRoute;el('clearRoute').onclick=clearRoute;el('openRouteBadge').onclick=()=>openPanel('route');
async function init(){try{const [locations,categories,regions]=await Promise.all(['data/locations.json','data/categories.json','data/regions.json'].map(u=>fetch(u).then(r=>{if(!r.ok)throw new Error(u);return r.json()})));state.locations=locations;state.categories=categories;state.regions=regions;categories.forEach(c=>{state.categoryMap.set(c.id,c);state.enabled.add(c.id)});regions.forEach(r=>state.regionMap.set(r.id,r));cleanSavedProgress();renderCategories();renderProgress();renderRoute();state.image.onload=()=>{state.imageReady=true;fitMap();scheduleDraw()};state.image.src='assets/world-map-4096.webp';resize();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}catch(err){console.error(err);toast('数据加载失败，请重新打开页面')}}
addEventListener('resize',resize);init();