(function(){'use strict';
const $=s=>document.querySelector(s);let locations=[],categories=new Map(),suggestions=[];
function distanceToSegment(p,a,b){const vx=b.atlas_x-a.atlas_x,vy=b.atlas_y-a.atlas_y,wx=p.atlas_x-a.atlas_x,wy=p.atlas_y-a.atlas_y,c1=vx*wx+vy*wy;if(c1<=0)return Math.hypot(p.atlas_x-a.atlas_x,p.atlas_y-a.atlas_y);const c2=vx*vx+vy*vy;if(c2<=c1)return Math.hypot(p.atlas_x-b.atlas_x,p.atlas_y-b.atlas_y);const t=c1/c2;return Math.hypot(p.atlas_x-(a.atlas_x+t*vx),p.atlas_y-(a.atlas_y+t*vy))}
function corridorDistance(p,route){let best=Infinity;for(let i=0;i<route.length-1;i++)best=Math.min(best,distanceToSegment(p,route[i],route[i+1]));return best}
function isCollectible(cat){const en=cat?.title_en||AtlasI18n?.english(cat?.title)||cat?.title||'';return /Chest|Glyph|Jizo|Kamon|Painting|Sumi|Dish|Music|Origami|Tea Bowl|Valuable|Weapon Part|Keys|Lost Page|Stockpile|Cultural Discovery/i.test(en)}
function render(){const box=$('#smartRouteResults');if(!box)return;if(!suggestions.length){box.innerHTML='<div class="smart-route-empty">路线附近暂无符合条件的未发现收集点。</div>';return}box.innerHTML=suggestions.slice(0,30).map((x,i)=>`<label class="smart-route-item"><input type="checkbox" data-suggest="${x.l.id}" checked><span><b>${x.l.title}</b><small>${x.cat.title} · 偏离路线约 ${Math.round(x.d*4096)} 地图单位</small></span><em>${i+1}</em></label>`).join('')}
function analyze(){const ids=JSON.parse(localStorage.getItem('atlas.route')||'[]'),done=new Set(JSON.parse(localStorage.getItem('atlas.discovered')||'[]'));const route=ids.map(id=>locations.find(x=>x.id===id)).filter(Boolean);if(route.length<2){suggestions=[];render();const n=$('#smartRouteCount');if(n)n.textContent='请先加入至少 2 个路线点';return}const width=Number($('#smartRouteWidth')?.value||12)/1000;const routeSet=new Set(ids);suggestions=locations.filter(l=>!routeSet.has(l.id)&&!done.has(l.id)&&isCollectible(categories.get(l.category_id))).map(l=>({l,cat:categories.get(l.category_id),d:corridorDistance(l,route)})).filter(x=>x.d<=width).sort((a,b)=>a.d-b.d);$('#smartRouteCount').textContent=`找到 ${suggestions.length} 个顺路收集点`;render()}
function addSelected(){const selected=[...document.querySelectorAll('[data-suggest]:checked')].map(x=>x.dataset.suggest);if(!selected.length)return;const route=JSON.parse(localStorage.getItem('atlas.route')||'[]');localStorage.setItem('atlas.route',JSON.stringify([...route,...selected.filter(id=>!route.includes(id))]));location.reload()}
async function init(){const panel=$('#routePanel');if(!panel)return;panel.insertAdjacentHTML('beforeend',`<section class="smart-route"><div class="smart-route-head"><div><small>探索规划</small><h3>顺路收集</h3></div><b id="smartRouteCount">等待分析</b></div><p>根据当前路线，寻找路线走廊附近尚未发现的收集品。</p><div class="smart-route-controls"><label>偏离范围 <input id="smartRouteWidth" type="range" min="5" max="35" value="12"><span id="smartRouteWidthLabel">12</span></label><button id="analyzeSmartRoute">分析路线</button><button class="primary" id="addSmartRoute">加入所选</button></div><div id="smartRouteResults" class="smart-route-results"></div></section>`);$('#smartRouteWidth').oninput=e=>$('#smartRouteWidthLabel').textContent=e.target.value;$('#analyzeSmartRoute').onclick=analyze;$('#addSmartRoute').onclick=addSelected;const [ls,cs]=await Promise.all([fetch('data/locations.json').then(r=>r.json()),fetch('data/categories.json').then(r=>r.json())]);locations=ls;categories=new Map(cs.map(c=>[c.id,c]));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();