const CACHE='atlas-alpha-0948-pages-v1-monitor-v11-ipad-canvas-2';
const ASSETS=['./','./index.html','./scan-monitor.html','./release-manifest.json','./atlas-bootstrap.js','./styles.css','./alpha03.css','./route.css','./smart-route.css','./atlas-smart-route-0932.css','./performance-071.css','./performance-074.css','./performance-092.css','./atlas-080.css','./atlas-typography-093.css','./atlas-ui-fix-0931.css','./atlas-liquid-nav-0933.css','./atlas-liquid-nav-0934.css','./atlas-nav-layout-0937.css','./atlas-controls-0938.css','./atlas-ipad-nav-0940.css','./atlas-ipad-canvas-hotfix-0948.css','./evidence-studio.css','./multiview-091.css','./public-library.css','./atlas-settings.css','./scan-monitor.css','./atlas-icons.js','./atlas-i18n.js','./location-names.js','./location-title-polish.js','./location-search-patch.js','./route-engine.js','./smart-route.js','./performance-071.js','./performance-074.js','./performance-092.js','./atlas-080.js','./atlas-ui-fix-0931.js','./atlas-liquid-nav-0933.js','./atlas-liquid-nav-0934.js','./atlas-controls-0938.js','./atlas-ipad-nav-0940.js','./atlas-ipad-canvas-hotfix-0948.js','./atlas-data-guard-0939.js','./page-zoom-guard.js','./atlas-hd-init.js','./atlas-hd-map.js','./atlas-hd-runtime.js','./atlas-settings.js','./scan-monitor.js','./atlas-evidence-studio.js','./atlas-evidence-workflow.js','./atlas-multiview-091.js','./atlas-public-library.js','./atlas-analysis-import.js','./app.js','./marker-state.js','./manifest.webmanifest','./icon-180.png','./icon-192.png','./icon-512.png','./assets/world-map-4096.webp','./data/locations.json','./data/categories.json','./data/regions.json','./data/building-templates.json','./data/public-source-library.json','./data/authorizations.json','./data/dada-ac-shadows-catalog.json','./data/eleven-game-world-ac-shadows-catalog.json','./data/analysis-index.json','./data/analysis-results/dada-temples-36.json','./data/rewards/reward-evidence-index.json','./data/rewards/reward-source-policy.json','./data/rewards/reward-record-schema.json','./data/rewards/reward-terminology-zh-CN.json'];
const CORE_DATA=/\/(?:data\/(?:locations|categories|regions)\.json|assets\/world-map-4096\.webp)(?:\?|$)/;
const LIVE_DATA=/\/data\/(?:runtime-progress\/[^?]+|batch-analysis\/(?:eleven-pilot-scan-status|eleven-pilot-scan-queue|eleven-pilot-recovery-report|eleven-pilot-watchdog-state|eleven-heartbeat-supervisor-state|scan-system-health)\.json)(?:\?|$)/;
const RELEASE_ASSET=/\/(?:atlas-bootstrap|atlas-liquid-nav-0934|atlas-controls-0938|atlas-ipad-nav-0940|atlas-ipad-canvas-hotfix-0948|atlas-analysis-import|atlas-settings|atlas-evidence-studio|atlas-ui-fix-0931|atlas-080|scan-monitor)\.(?:js|css)(?:\?|$)|\/data\/rewards\/(?:reward-evidence-index|reward-source-policy|reward-record-schema|reward-terminology-zh-CN)\.json(?:\?|$)|\/(?:release-manifest|scan-monitor)\.json(?:\?|$)/;
const MONITOR_NAV=/\/scan-monitor\.html(?:\?|$)/;
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE).then(cache=>Promise.allSettled(ASSETS.map(asset=>cache.add(asset)))))});
self.addEventListener('activate',event=>{event.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))),self.clients.claim()]))});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;const request=event.request;const pathname=new URL(request.url).pathname;
  if(request.mode==='navigate'){const fallback=MONITOR_NAV.test(pathname)?'./scan-monitor.html':'./index.html';event.respondWith(fetch(request,{cache:'no-store'}).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(fallback,response.clone()));return response}).catch(()=>caches.match(fallback)));return;}
  if(LIVE_DATA.test(pathname)){event.respondWith(fetch(request,{cache:'no-store'}).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(request,response.clone()));return response}).catch(()=>caches.match(request,{ignoreSearch:true})));return;}
  if(RELEASE_ASSET.test(pathname)){event.respondWith(fetch(request,{cache:'reload'}).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(request,response.clone()));return response}).catch(()=>caches.match(request,{ignoreSearch:true})));return;}
  if(CORE_DATA.test(pathname)){event.respondWith(caches.match(request,{ignoreSearch:true}).then(cached=>{const network=fetch(request,{cache:'no-store'}).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(request,response.clone()));return response});if(cached){event.waitUntil(network.catch(()=>{}));return cached}return network}));return;}
  event.respondWith(fetch(request).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(request,response.clone()));return response}).catch(()=>caches.match(request,{ignoreSearch:true})));
});