#!/usr/bin/env python3
"""Review the first eight direct shrine anchor candidates with two independent vision models.

Only exact popup crops from the authorized video are sent to GitHub Models. Candidate IDs are
never generated by a model; each reviewer answers whether the visible popup title matches the
expected Chinese label. Repository output contains text, timestamps, hashes and decisions only.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import re
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import cv2

ROOT = Path(__file__).resolve().parents[1]
CANDIDATE_PATH = ROOT / "data/geospatial/dada-shrines-27-anchor-candidates.json"
CENSUS_PATH = ROOT / "data/geospatial/dada-shrines-popup-event-census.json"
DEFAULT_OUTPUT = ROOT / "data/geospatial/dada-shrines-direct-review-batch01.json"
ENDPOINT = "https://models.github.ai/inference/chat/completions"
MODELS = ("openai/gpt-4.1-mini", "openai/gpt-4o-mini")
ORDINALS = tuple(range(1, 9))
EVENTS_PER_REQUEST = 4
MINIMUM_CONFIDENCE = 0.92


def now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise RuntimeError(f"expected object in {path}")
    return value


def write(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    temporary.replace(path)


def parse_json_object(text: str) -> dict[str, Any]:
    cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", text.strip(), flags=re.IGNORECASE | re.DOTALL)
    start, end = cleaned.find("{"), cleaned.rfind("}")
    if start < 0 or end < start:
        raise ValueError("model response contains no JSON object")
    value = json.loads(cleaned[start:end + 1])
    if not isinstance(value, dict):
        raise ValueError("model response root is not an object")
    return value


def extract_popup_crops(video: Path, output_dir: Path) -> tuple[list[dict[str, Any]], str]:
    package = load(CANDIDATE_PATH)
    census = load(CENSUS_PATH)
    if package.get("status") != "shrine-anchor-candidate-package-ready":
        raise RuntimeError("candidate package is not ready")
    if census.get("status") != "popup-event-census-complete":
        raise RuntimeError("popup event census is not complete")

    candidates = {int(row["ordinal"]): row for row in package["directPopupCandidates"]}
    events = {int(row["event"]): row for row in census["events"]}
    capture = cv2.VideoCapture(str(video))
    if not capture.isOpened():
        raise RuntimeError("unable to open authorized shrine video")
    fps = float(capture.get(cv2.CAP_PROP_FPS) or 30.0)
    output_dir.mkdir(parents=True, exist_ok=True)
    rows: list[dict[str, Any]] = []
    try:
        for ordinal in ORDINALS:
            candidate = candidates[ordinal]
            event_number = int(candidate["event"])
            event = events[event_number]
            second = float(event["representativeTimeSeconds"])
            expected_second = float(candidate["representativeTimeSeconds"])
            if abs(second - expected_second) > 0.01:
                raise RuntimeError(f"candidate/event time mismatch for ordinal {ordinal}")
            capture.set(cv2.CAP_PROP_POS_FRAMES, round(second * fps))
            ok, frame = capture.read()
            if not ok or frame is None:
                raise RuntimeError(f"unable to read frame at {second:.3f}s")
            box = event["box"]
            x, y = int(box["x"]), int(box["y"])
            width, height = int(box["width"]), int(box["height"])
            pad = 10
            x0, y0 = max(0, x - pad), max(0, y - pad)
            x1, y1 = min(frame.shape[1], x + width + pad), min(frame.shape[0], y + height + pad)
            crop = frame[y0:y1, x0:x1]
            if crop.size == 0:
                raise RuntimeError(f"empty popup crop for ordinal {ordinal}")
            scale = max(1.0, min(2.5, 900.0 / max(1, crop.shape[1])))
            if scale > 1.01:
                crop = cv2.resize(
                    crop,
                    (round(crop.shape[1] * scale), round(crop.shape[0] * scale)),
                    interpolation=cv2.INTER_CUBIC,
                )
            filename = f"S{ordinal:02d}-E{event_number:02d}-{second:.3f}s-popup.jpg"
            path = output_dir / filename
            if not cv2.imwrite(str(path), crop, [cv2.IMWRITE_JPEG_QUALITY, 94]):
                raise RuntimeError(f"unable to write popup crop {filename}")
            rows.append({
                "ordinal": ordinal,
                "event": event_number,
                "representativeTimeSeconds": round(second, 3),
                "expectedLabelZhCN": candidate["visibleLabelZhCN"],
                "locationId": candidate["locationId"],
                "candidateTitle": candidate["candidateTitle"],
                "filename": filename,
                "sha256": sha256_file(path),
                "width": int(crop.shape[1]),
                "height": int(crop.shape[0]),
            })
    finally:
        capture.release()

    fingerprint_source = json.dumps(
        {
            "packageSha256": sha256_file(CANDIDATE_PATH),
            "censusSha256": sha256_file(CENSUS_PATH),
            "crops": [{"ordinal": row["ordinal"], "sha256": row["sha256"]} for row in rows],
            "models": MODELS,
            "threshold": MINIMUM_CONFIDENCE,
        },
        sort_keys=True,
    ).encode("utf-8")
    return rows, sha256_bytes(fingerprint_source)


def request_batch(model: str, batch: list[dict[str, Any]], root: Path, token: str) -> dict[str, Any]:
    instructions = [
        "You are verifying exact Chinese place-name text in cropped Assassin's Creed Shadows map popups.",
        "Return JSON only with shape: {\"reviews\":[{\"ordinal\":1,\"matchesExpectedLabel\":true,\"visibleLabel\":\"...\",\"confidence\":0.95,\"reasonZhCN\":\"...\"}]}",
        "Read only the popup image itself. Ignore icons, background map detail and any assumed game order.",
        "Set matchesExpectedLabel=true only when the visible Chinese title directly matches the supplied expected label.",
        "Minor Simplified/Traditional glyph variants are acceptable only when the place name is otherwise exact.",
        "Use confidence >=0.92 only when the title is directly readable. Otherwise return false with lower confidence.",
        "The model must not invent or choose a location ID.",
        "Expected labels:",
    ]
    for row in batch:
        instructions.append(
            f"- ordinal {row['ordinal']}: expected {row['expectedLabelZhCN']} ({row['candidateTitle']})"
        )
    content: list[dict[str, Any]] = [{"type": "text", "text": "\n".join(instructions)}]
    for row in batch:
        image_url = "data:image/jpeg;base64," + base64.b64encode((root / row["filename"]).read_bytes()).decode("ascii")
        content.append({"type": "text", "text": f"IMAGE FOR ORDINAL {row['ordinal']}"})
        content.append({"type": "image_url", "image_url": {"url": image_url}})

    payload = {
        "model": model,
        "temperature": 0.0,
        "max_tokens": 1800,
        "messages": [
            {"role": "system", "content": "Be conservative and transcribe visible text exactly."},
            {"role": "user", "content": content},
        ],
    }
    request = urllib.request.Request(
        ENDPOINT,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=90) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")[:600]
        raise RuntimeError(f"HTTP {error.code}: {detail}") from error
    value = parse_json_object(body["choices"][0]["message"]["content"])
    raw_reviews = value.get("reviews")
    if not isinstance(raw_reviews, list):
        raise ValueError("model response reviews is not a list")
    expected = {int(row["ordinal"]): row for row in batch}
    reviews: list[dict[str, Any]] = []
    seen: set[int] = set()
    for raw in raw_reviews:
        if not isinstance(raw, dict):
            continue
        ordinal = int(raw.get("ordinal") or 0)
        if ordinal not in expected or ordinal in seen:
            continue
        seen.add(ordinal)
        matches = raw.get("matchesExpectedLabel") is True
        confidence = max(0.0, min(1.0, float(raw.get("confidence") or 0.0)))
        reviews.append({
            "ordinal": ordinal,
            "matchesExpectedLabel": matches,
            "visibleLabel": str(raw.get("visibleLabel") or "").strip(),
            "confidence": round(confidence, 4),
            "reasonZhCN": str(raw.get("reasonZhCN") or "").strip(),
            "selectedLocationId": expected[ordinal]["locationId"] if matches else None,
        })
    if seen != set(expected):
        raise ValueError(f"model response did not cover exact batch ordinals: {sorted(seen)}")
    reviews.sort(key=lambda row: row["ordinal"])
    return {
        "model": model,
        "ordinals": sorted(expected),
        "reviewedAt": now(),
        "reviews": reviews,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--video", required=True)
    parser.add_argument("--work-dir", required=True)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    video = Path(args.video).resolve()
    work_dir = Path(args.work_dir).resolve()
    output = Path(args.output).resolve()
    evidence, fingerprint = extract_popup_crops(video, work_dir)
    evidence_by_ordinal = {row["ordinal"]: row for row in evidence}

    existing_packets: dict[tuple[str, tuple[int, ...]], dict[str, Any]] = {}
    if output.is_file():
        try:
            previous = load(output)
            if previous.get("evidenceFingerprint") == fingerprint:
                for packet in previous.get("reviewPackets", []):
                    key = (str(packet.get("model")), tuple(int(value) for value in packet.get("ordinals", [])))
                    if key[0] in MODELS and key[1]:
                        existing_packets[key] = packet
        except (OSError, ValueError, TypeError, KeyError):
            existing_packets = {}

    token = os.environ.get("GITHUB_TOKEN", "").strip()
    if not token:
        raise RuntimeError("GITHUB_TOKEN is required")

    packets: list[dict[str, Any]] = []
    errors: list[dict[str, Any]] = []
    requested = 0
    reused = 0
    batches = [list(ORDINALS[index:index + EVENTS_PER_REQUEST]) for index in range(0, len(ORDINALS), EVENTS_PER_REQUEST)]
    for model in MODELS:
        for ordinals in batches:
            key = (model, tuple(ordinals))
            if key in existing_packets:
                packets.append(existing_packets[key])
                reused += 1
                continue
            requested += 1
            batch = [evidence_by_ordinal[ordinal] for ordinal in ordinals]
            try:
                packets.append(request_batch(model, batch, work_dir, token))
            except Exception as error:
                errors.append({"model": model, "ordinals": ordinals, "error": str(error)[:1000]})
            time.sleep(3)

    model_reviews: dict[str, dict[int, dict[str, Any]]] = {model: {} for model in MODELS}
    for packet in packets:
        model = packet["model"]
        for review in packet["reviews"]:
            model_reviews[model][int(review["ordinal"])] = review

    consensus: list[dict[str, Any]] = []
    confirmed_count = 0
    for ordinal in ORDINALS:
        reviews = [model_reviews[model].get(ordinal) for model in MODELS]
        complete = all(review is not None for review in reviews)
        confirmed = complete and all(
            review["matchesExpectedLabel"] is True
            and review["selectedLocationId"] == evidence_by_ordinal[ordinal]["locationId"]
            and float(review["confidence"]) >= MINIMUM_CONFIDENCE
            for review in reviews
        )
        if confirmed:
            confirmed_count += 1
        consensus.append({
            "ordinal": ordinal,
            "event": evidence_by_ordinal[ordinal]["event"],
            "expectedLabelZhCN": evidence_by_ordinal[ordinal]["expectedLabelZhCN"],
            "locationId": evidence_by_ordinal[ordinal]["locationId"],
            "status": "confirmed" if confirmed else ("unresolved" if complete else "partial-review"),
            "promotionReady": confirmed,
            "reviewers": {
                model: model_reviews[model].get(ordinal)
                for model in MODELS
            },
        })

    successful_models = sum(
        1 for model in MODELS if all(ordinal in model_reviews[model] for ordinal in ORDINALS)
    )
    result = {
        "schemaVersion": 1,
        "generatedAt": now(),
        "status": "complete" if successful_models == len(MODELS) else "partial-review",
        "stage": "direct-shrine-popup-independent-review-batch01",
        "evidenceFingerprint": fingerprint,
        "batch": {"ordinals": list(ORDINALS), "eventsPerRequest": EVENTS_PER_REQUEST},
        "policy": {
            "models": list(MODELS),
            "minimumIndependentModels": 2,
            "minimumConfidencePerModel": MINIMUM_CONFIDENCE,
            "programmaticLocationIdMapping": True,
            "coordinatesPromoted": False,
            "canonicalAnchorModified": False,
        },
        "counts": {
            "candidateCount": len(ORDINALS),
            "confirmed": confirmed_count,
            "unresolved": len(ORDINALS) - confirmed_count if successful_models == len(MODELS) else 0,
            "successfulReviewerModels": successful_models,
            "failedReviewerModels": len(MODELS) - successful_models,
            "requestedBatchCallsThisRun": requested,
            "reusedBatchCallsThisRun": reused,
            "persistedBatchPackets": len(packets),
        },
        "evidence": evidence,
        "reviewPackets": packets,
        "consensus": consensus,
        "errors": errors,
        "privacy": {
            "repositoryContainsPixels": False,
            "transientPopupCropsDeletedByWorkflow": True,
        },
    }
    write(output, result)
    print(json.dumps({"status": result["status"], "counts": result["counts"]}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
